apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-service
spec:
  selector:
    matchLabels:
      app: at-service
  replicas: 1
  template:
    metadata:
      labels:
        app: at-service
    spec:
      containers:
        - name: at-service
          image: thiagormg/at-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_URI
              value: "http://EUREKA-SERVER:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: at-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31001
  selector:
    app: at-service