apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculo-service
spec:
  selector:
    matchLabels:
      app: veiculo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: veiculo-service
    spec:
      containers:
        - name: veiculo-service
          image: thiagormg/veiculo-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER_URI
              value: "http://EUREKA-SERVER:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: veiculo-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    app: veiculo-service